<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <Platforms>x64</Platforms>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Commandline" Version="2.0.8" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\TwsBridge\TwsBridge.vcxproj" />
  </ItemGroup>

</Project>
